### ISSUE TITLE
安全：更新机器人名称时，会返回token: "puppet_padplus_ebxxx"

### ISSUE THREAD

**Issue by guoxiangke** [beclass/wxbot#1]
![image](https://user-images.githubusercontent.com/1160703/83329619-1864cf80-a2bd-11ea-86f4-ed3336a3e320.png)
![image](https://user-images.githubusercontent.com/1160703/83329658-49dd9b00-a2bd-11ea-8187-7f88d6df72f4.png)

是否可以过滤掉呢

**Comment by beclass** [comment]
@guoxiangke push上去了，虽然自己用倒也没关系哈
