### ISSUE TITLE
Cannot find module 'local' 

### ISSUE THREAD

**Issue by linsage** [beclass/wxbot#6]
`npm run dev `

Error: Cannot find module 'local'
  Require stack:
  - node_modules/@nuxtjs/auth/lib/module/index.js
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/nuxt/dist/nuxt.js
  - server/index.js
  at ModuleContainer.resolveProvider 

看起来是local文件，是否要调整配置或者编译什么，对nuxtjs不太熟悉，请指教，谢谢。

**Comment by linsage** [comment]
猜测是cnpm问题和包版本环境问题，已调整解决。

**Comment by star8ks** [comment]
@linsage 请问是如何解决的？我也碰到相同的问题。

**Comment by linsage** [comment]
@ray7551 怀疑我环境 cnpm 和 npm 混用问题，然后清理一下包缓存，用npm试了几次就可以了

**Comment by star8ks** [comment]
@linsage 我是把 local 目录移出去以后就没有问题了。
